Print the count of vowels in the given string using while loop

In [1]:
string = input("Enter a string: ")
vowels = "aeiouAEIOU"
count = 0
i = 0
while i<len(string):
    if string[i] in vowels:
        count+=1
    i+=1
print(f"{string} has {count} vowels")

here is An apple has 6 vowels


Print the date by adding the given number of days

In [2]:
from datetime import datetime, timedelta

def func1(date, days_to_add):
    new_date = date + timedelta(days_to_add)
    return new_date

In [3]:
date_entry1 = input("Enter the first date (YYYY-MM-DD): ")
year1, month1, day1 = map(int, date_entry1.split('-'))
date1 = datetime(year1, month1, day1)

days_input = input("Enter number of days to add: ")

In [4]:
try:
    days_to_add = int(days_input)
except ValueError:
    print("Invalid input for number of days. Please enter a valid integer.")
    exit()

new_date = func1(date1, days_to_add)

print(f"Original date: {date1.date()}")
print(f"New date after adding {days_to_add} days: {new_date.date()}")

Original date: 2020-10-10
New date after adding 5 days: 2020-10-15


Write a program to perfrom below functions Consider a list (list = []). You can perform the following commands:
 
insert i e: Insert integer  at position . <br>
print: Print the list.<br>
remove e: Delete the first occurrence of integer .<br>
append e: Insert integer  at the end of the list.<br>
sort: Sort the list.<br>
pop: Pop the last element from the list.<br>
reverse: Reverse the list.

In [5]:
my_list = [1,2,3,4,5,4]

In [6]:
def insert_int(i, e):
    global my_list
    my_list.insert(i, e)
    print(f"{e} inserted successfully at position {i}")

def print_int():
    global my_list
    print("Current list:", my_list)

def remove_int(e):
    global my_list
    if e in my_list:
        my_list.remove(e)
        print("Removed")
    else:
        print(f"{e} is not in the list.")

def append_int(e):
    global my_list
    my_list.append(e)
    print("Appended: ",my_list)
def sort_int():
    global my_list
    my_list.sort()
    print("sorted list: ",my_list)

def pop_int():
    global my_list
    if my_list:
        my_list.pop()
        print("Popped, new list : ",my_list)
    else:
        print("List is empty, cannot pop.")
        
def reverse_int():
    global my_list
    my_list.reverse()
    print("Reversed list: ",my_list)

In [7]:
ans = True
while ans:
    print("""
    1. Insert: insert integer i at position e
    2. Print: print the list
    3. Remove: delete integer 'e' at first occurrence
    4. Append: insert integer at the end of list
    5. Sort: sort the list
    6. Pop: pop the last element from the list
    7. Reverse: reverse the list
    8. Exit
    """)
    ans = input("What would you like to do? ")

    if ans == "1":
        i = int(input("Enter position i: "))
        e = int(input("Enter integer e: "))
        insert_int(i, e)
    elif ans == "2":
        print_int()
    elif ans == "3":
        e = int(input("Enter integer e to remove: "))
        remove_int(e)
    elif ans == "4":
        e = int(input("Enter integer to append: "))
        append_int(e)
    elif ans == "5":
        sort_int()
    elif ans == "6":
        pop_int()
    elif ans == "7":
        reverse_int()
    elif ans == "8":
        print("Exiting program.")
        ans = False
    else:
        print("\nNot Valid Choice. Try again.")


    1. Insert: insert integer i at position e
    2. Print: print the list
    3. Remove: delete integer 'e' at first occurrence
    4. Append: insert integer at the end of list
    5. Sort: sort the list
    6. Pop: pop the last element from the list
    7. Reverse: reverse the list
    8. Exit
    
Current list: [1, 2, 3, 4, 5, 4]

    1. Insert: insert integer i at position e
    2. Print: print the list
    3. Remove: delete integer 'e' at first occurrence
    4. Append: insert integer at the end of list
    5. Sort: sort the list
    6. Pop: pop the last element from the list
    7. Reverse: reverse the list
    8. Exit
    
Exiting program.


write a program to read a csv file and display - Pandas

In [8]:
import pandas as pd
import numpy as np

df = pd.read_csv("cardata.csv")

In [9]:
df.head()

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0     ritz  2014           3.35           5.59       27000    Petrol   
1      sx4  2013           4.75           9.54       43000    Diesel   
2     ciaz  2017           7.25           9.85        6900    Petrol   
3  wagon r  2011           2.85           4.15        5200    Petrol   
4    swift  2014           4.60           6.87       42450    Diesel   

  Seller_Type Transmission  Owner  
0      Dealer       Manual      0  
1      Dealer       Manual      0  
2      Dealer       Manual      0  
3      Dealer       Manual      0  
4      Dealer       Manual      0

write a program to return numbers of weeks in a give year and month

In [12]:
import calendar
def num_weeks_in_month(year, month):
    month_matrix = calendar.monthcalendar(year, month)
    num_weeks = len(month_matrix)

    return num_weeks

year_input = int(input("Enter the year: "))
month_input = int(input("Enter the month (1-12): "))

if month_input < 1 or month_input > 12:
    print("Invalid month input. Please enter a number between 1 and 12.")
else:
    num_weeks = num_weeks_in_month(year_input, month_input)
    print(f"Number of weeks in {calendar.month_name[month_input]}, {year_input}: {num_weeks}")

Number of weeks in July, 2024: 5


Write a program to accept length of array and accept the numbers as per given length and print the second highest of it

In [13]:
def find_second_highest(arr):
    max_num = arr[0]
    second_max = float('-inf')  
    for num in arr:
        if num > max_num:
            second_max = max_num
            max_num = num
        elif num > second_max and num != max_num:
            second_max = num

    return second_max

In [14]:
length = int(input("Enter the length of the array: "))
arr = []
for i in range(length):
    num = int(input(f"Enter element {i+1}: "))
    arr.append(num)

if length < 2:
    print("Array length should be at least 2 to find the second highest.")
else:
    second_highest = find_second_highest(arr)
    if second_highest == float('-inf'):
        print("There is no second highest number in the array.")
    else:
        print(f"The second highest number in the array is: {second_highest}")


The second highest number in the array is: 2


Write a program to filter and display the values from dictionary based on given input

In [15]:
my_dict = {"Anushka":2002,"Pooja":1972,"Anya":2007,"Vivek":1972}

In [16]:
name = input("Enter name to find DOB")
if name in my_dict:
    print(f"{name} has a DOB Year : {my_dict[name]}")

Anushka has a DOB Year : 2002


Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

In [26]:
import numpy as np
arr = np.arange(2,11)
m=arr.reshape(3,3)
print(m)
print(m.ndim)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
2


Write a NumPy program to append values to the end of an array.

In [18]:
l = [1,2,3]
a = int(input("Enter value to be appended"))
x =np.append(l,a)
print(x)

[1 2 3 6]
